name: madinah

on:
  schedule:
    - cron: '*/60 * * * *'

  pull_request:
    branches: [ main ]

  workflow_dispatch:
jobs:

  runCode:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Grab Link

        run: |
          git config --global user.email "freedomusertech@gmail.com"
          git config --global user.name "freedomusertech"
          chmod +x madinah.sh && ./madinah.sh
          git add -A
          git commit -m "links are updated."
          git push
